### ISSUE TITLE
kernel/built-in.o: In function `kernel_restart': /home/android/lineage-16.0/out/target/product/matisselte/obj/KERNEL_OBJ/../../../../../../kernel/samsung/msm8226-n/kernel/sys.c:446: undefined reference to `sec_param_restart_reason' /home/android/lineage-16.0/kernel/samsung/msm8226-n/Makefile:887: recipe for target '.tmp_vmlinux1' failed make[1]: *** [.tmp_vmlinux1] Error 1 Makefile:130: recipe for target 'sub-make' failed make: *** [sub-make] Error 2 make: Leaving directory '/home/android/lineage-16.0/kernel/samsung/msm8226-n' ninja: build stopped: subcommand failed. 20:13:23 ninja failed with: exit status 1

### ISSUE THREAD

**Issue by BAProductions** [S3NEO/android_kernel_samsung_msm8226#1]
https://github.com/S3NEO/android_kernel_samsung_msm8226/blob/5fd33b9c9ffa95d4594d946326d7dc811b2f3f4a/kernel/sys.c#L446

**Comment by BAProductions** [comment]
kernel/built-in.o: In function `kernel_restart': /home/android/lineage-16.0/out/target/product/matisselte/obj/KERNEL_OBJ/../../../../../../kernel/samsung/msm8226-n/kernel/sys.c:446: undefined reference to `sec_param_restart_reason' /home/android/lineage-16.0/kernel/samsung/msm8226-n/Makefile:887: recipe for target '.tmp_vmlinux1' failed make[1]: *** [.tmp_vmlinux1] Error 1 Makefile:130: recipe for target 'sub-make' failed make: *** [sub-make] Error 2 make: Leaving directory '/home/android/lineage-16.0/kernel/samsung/msm8226-n' ninja: build stopped: subcommand failed. 20:13:23 ninja failed with: exit status 1

**Comment by fcuzzocrea** [comment]
Although is strange that you exprrice that issue, build from the -s6e8ecec branch for now if you're building for s3neo

**Comment by fcuzzocrea** [comment]
Oh no, you're on Matisse. That's very strange as I tried build for all the devices. Which defconfig are you using ?

**Comment by fcuzzocrea** [comment]
I think CONFIG_RESTART_REASON_SEC_PARAM has to be removed from the defconfig, if present, my bad that I didnt did that before, but I dont have the device.

The relevant section in defconfig should be like :

CONFIG_SEC_RESTRICT_ROOTING is not set
CONFIG_RESTART_REASON_SEC_PARAM is not set
CONFIG_RESTART_REASON_DDR is not set

Instead of 

CONFIG_SEC_RESTRICT_ROOTING is not set
CONFIG_RESTART_REASON_SEC_PARAM=y
CONFIG_RESTART_REASON_DDR is not set

Also I would also advise to add : https://github.com/S3NEO/android_kernel_samsung_msm8226/commit/5e045cef6cde523d0e1f5d0c66cb8c02a9b4bdbd#diff-da8421ad27e9762e7e95e84e6748b1d3

and 

https://github.com/S3NEO/android_kernel_samsung_msm8226/commit/b230966a1cb0d1d59e288c77ccf537ee796b295d#diff-da8421ad27e9762e7e95e84e6748b1d3

on matisse defconfig.

The rest should be fine (I hope)
